# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts

# Create app directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install pnpm globally
RUN npm install -g pnpm

# Install dependencies without running lifecycle scripts
RUN pnpm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project using tsc and set execute permission on the built entrypoint
RUN pnpm run build

# Expose any port if necessary (not required by MCP spec)

# Start the MCP server
CMD ["node", "./build/index.js"]
